apiVersion: v1
kind: ConfigMap
metadata:
  name: employeeapp-configmap
  namespace: employeeapp
data:
  application.properties: |
    server.port=9092
    spring.datasource.url=jdbc:postgresql://employeeapp-service:5432/db-kiii
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}

